# Generated by Django 3.1.2 on 2020-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirurl',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
