# Generated by Django 3.1.2 on 2020-10-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0002_auto_20201010_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ack_subpublicationmenu',
            name='publicationicon',
        ),
    ]
