# Generated by Django 3.1.2 on 2020-10-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0003_remove_ack_subpublicationmenu_publicationicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_publicationname',
            name='submenu_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
