# Generated by Django 3.1.2 on 2020-10-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0004_auto_20201013_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ack_subguidelinesmenu',
            name='file',
        ),
    ]
