# Generated by Django 3.1.2 on 2020-10-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0005_remove_ack_subguidelinesmenu_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_guidelinesname',
            name='submenu_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
