# Generated by Django 3.1.2 on 2020-10-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0006_auto_20201013_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ack_subnavy_instructionssmenu',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ack_subnavy_orderssmenu',
            name='file',
        ),
    ]
