# Generated by Django 3.1.2 on 2020-10-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0007_auto_20201013_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_navyname',
            name='submenu_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
