# Generated by Django 3.1.2 on 2020-10-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0008_auto_20201013_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ack_navyname',
            name='parent',
        ),
    ]
