# Generated by Django 3.1.2 on 2020-10-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0009_remove_ack_navyname_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_navyname',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navyOrders_name', to='acknowledge.ack_subnavy_orderssmenu'),
        ),
    ]
