# Generated by Django 3.1.2 on 2020-10-17 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0010_auto_20201013_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_submenu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='policy/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF'])]),
        ),
    ]
