# Generated by Django 3.1.2 on 2020-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0012_auto_20201017_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_subpublicationmenu',
            name='submenu_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
