# Generated by Django 3.1.2 on 2020-10-17 17:50

import acknowledge.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0016_auto_20201017_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_subnavy_instructionssmenu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='navy_instructionfile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF', 'png', 'jpg', 'JPEG']), acknowledge.models.validate_image]),
        ),
    ]
