# Generated by Django 3.1.2 on 2020-10-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0020_auto_20201026_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_related', to='acknowledge.ack_submenu'),
        ),
    ]
